name: Publish Packages

on:
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish:
    name: Publish Packages
    runs-on: ubuntu-latest
    environment: publish
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # To get all tags
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Check for changesets
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Fail if changesets found
        if: steps.changesets.outputs.hasChangesets == 'true'
        run: |
          echo "Changesets found. Merge Version Packages PR before publishing."
          exit 1
      - name: Publish
        if: steps.changesets.outputs.hasChangesets == 'false'
        run: npm run publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
