name: Version Packages

on:
  push:
    branches:
      - master

concurrency:
  group: version-or-publish-${{ github.ref }}
  cancel-in-progress: false

jobs:
  version:
    name: Create Version Packages PR
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # To get all tags
          ref: ${{ github.ref }}
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Create Version Packages Pull Request
        uses: changesets/action@v1
        with:
          title: Version Packages
          commit: Version Packages
          version: npm run version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
